name:                herp-logger
version:             0.1.0.0
#github:              "herp-inc/herp-hslib"
#license:             BSD3
#author:              "ruicc"
#maintainer:          "kousuke.ruichi@herp.co.jp"
#copyright:           "2021 HERP, Inc"

#extra-source-files:
#- README.md
#- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/herp-inc/herp-hslib#readme>

library:
  source-dirs:
  - src
  - gen-proto
  other-modules:
  - Protos.Herp.Log.HttpLog
  dependencies:
  - herp-util

  - base >= 4.7 && < 5
  - text
  - bytestring
  - vector
  - containers
  - unordered-containers
  - safe
  - hashable
  - uuid
  - aeson
  - base64-bytestring
  - time
  - mono-traversable
  - binary
  - lrucaching
  - case-insensitive
  - unix-compat
  - unix-time

  # Control
  - deepseq
  - exceptions
  - rio
  - transformers
  - mtl

  # Argument Parser
  - optparse-generic

  # Concurrent
  - safe-exceptions
  - stm
  - async

  # Lens
  - generic-lens
  - generic-lens-core
  - lens

  # Sentry
  - raven-haskell == 0.1.4.*
  - fast-logger
  - http-conduit
  - gitrev

  # protobuf
  - proto3-wire
  - proto3-suite

  # web
  - wai

  default-extensions:
  - ConstraintKinds
  - DeriveDataTypeable
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveTraversable
  - DuplicateRecordFields
  - ExplicitForAll
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - LambdaCase
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - NamedWildCards
  - NegativeLiterals
  #- NoImplicitPrelude
  - NumericUnderscores
  - OverloadedStrings
  - PackageImports
  - PartialTypeSignatures
  - PatternSynonyms
  - PolyKinds
  - QuasiQuotes
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - Strict
  - StrictData
  - TemplateHaskell
  - TupleSections
  - TypeApplications
  - TypeFamilies
  #- OverloadedLists
  - TypeOperators
  - DeriveAnyClass
  - DataKinds
  - GADTs
  - BangPatterns
  - OverloadedLabels
  - GeneralizedNewtypeDeriving
  - DerivingStrategies
  - BlockArguments
  - ImplicitParams
  - InstanceSigs
  - ImportQualifiedPost

#executables:
#  herp-hslib-exe:
#    main:                Main.hs
#    source-dirs:         app
#    ghc-options:
#    - -threaded
#    - -rtsopts
#    - -with-rtsopts=-N
#    dependencies:
#    - herp-hslib
#
#tests:
#  herp-hslib-test:
#    main:                Spec.hs
#    source-dirs:         test
#    ghc-options:
#    - -threaded
#    - -rtsopts
#    - -with-rtsopts=-N
#    dependencies:
#    - herp-hslib
